version: '3.9'

services:
  dash-packager:
    build:
      context: scripts
    container_name: dash-packager
    hostname: dash-packager
    volumes: 
      - dash-data:/dash-data
    ports:
      - 1935:1935
    restart: always
  dash-server:
    build:
      context: .
    container_name: dash-server
    hostname: dash-server
    volumes:
      - dash-data:/dash-data
    ports:
      - 5000:5000
    restart: always
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    hostname: reverse-proxy
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
volumes:
  dash-data: {}