version: '3.9'

services:
  dash-packager:
    build:
      context: scripts
    container_name: dash-packager
    hostname: dash-packager
    volumes: 
      - dash-data:/dash-data
    ports:
      - 1935:1935
    restart: always
  dash-server:
    build:
      context: .
    container_name: dash-server
    hostname: dash-server
    volumes:
      - dash-data:/dash-data
    ports:
      - 5000:5000
    restart: always
  cache-server:
    image: varnish
    container_name: cache-server
    hostname: cache-server
    ports:
      - 80:80
    restart: always
    tmpfs:
      - /var/lib/varnish:exec
    volumes:
      - ./conf/default.vcl:/etc/varnish/default.vcl
volumes:
  dash-data: {}